# Generated by Django 2.2.2 on 2019-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
